name: Auto merge the triggered PRs

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find one PR matching "archiving JSON file" in title
        id: find_pr
        run: |
          echo "Searching for one open PR with title matching 'archiving JSON file'"

          # Using the exact line you requested with necessary fixes:
          MATCHING_TITLE=$(gh search prs --repo "$GITHUB_REPOSITORY" 'archiving JSON file' --state open --limit 1 --json title,body --jq '.[].title | match("archiving JSON file").string')

          if [ -z "$MATCHING_TITLE" ]; then
            echo "No matching PR found."
            echo "found=false" >> $GITHUB_OUTPUT
          else
            echo "Found matching PR with title: $MATCHING_TITLE"
            # Find PR number(s) that match this title:
            PR_NUMBER=$(gh pr list --repo "$GITHUB_REPOSITORY" --state open --json number,title --jq ".[] | select(.title == \"$MATCHING_TITLE\") | .number" | head -n1)

            if [ -z "$PR_NUMBER" ]; then
              echo "No PR number found for matched title."
              echo "found=false" >> $GITHUB_OUTPUT
            else
              echo "Matching PR number: $PR_NUMBER"
              echo "$PR_NUMBER" > pr_list.txt
              echo "found=true" >> $GITHUB_OUTPUT
            fi
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR
        if: steps.find_pr.outputs.found == 'true'
        run: |
          while read PR; do
            echo "Merging PR #$PR..."
            gh pr merge "$PR" --merge --delete-branch || echo "Failed to merge PR #$PR"
          done < pr_list.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
