name: Auto merge the triggered PRs

on:
  pull_request:
    types:
      - opened

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'akshkuma'

    steps:
      - name: Check PR Title
        id: check_title
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          echo "PR title: $TITLE"

          if [ "$TITLE" = "Automated PR: Add new file" ]; then
            echo "should_merge=true" >> $GITHUB_OUTPUT
          else
            echo "should_merge=false" >> $GITHUB_OUTPUT
          fi

      - name: Auto-approve PR
        if: steps.check_title.outputs.should_merge == 'true'
        run: |
          gh pr review ${{ github.event.pull_request.html_url }} --approve
        env:
          GH_TOKEN: ${{ secrets.PR_ACCESS_TOKEN }}

      - name: Auto-merge PR
        if: steps.check_title.outputs.should_merge == 'true'
        run: |
          gh pr merge ${{ github.event.pull_request.html_url }} --merge --delete-branch
        env:
          GH_TOKEN: ${{ secrets.PR_ACCESS_TOKEN }}
