name: Auto merge PRs matching "archiving JSON file"

on: 
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find open PRs containing "archiving JSON file"
        id: find_prs
        run: |
          echo "Searching open PRs with title containing 'archiving JSON file'"

          # Search open PRs in this repo with the phrase in title (case-insensitive)
          # Adjust --limit or query as needed to get all relevant PRs
          PRS_JSON=$(gh search prs --repo "$GITHUB_REPOSITORY" 'archiving JSON file' --state open --limit 50 --json number,title)

          # Extract PR numbers where title matches the phrase (case-insensitive)
          MATCHING_PRS=($(echo "$PRS_JSON" | jq -r '.[] | select(.title | test("archiving JSON file"; "i")) | .number'))

          if [ ${#MATCHING_PRS[@]} -eq 0 ]; then
            echo "No matching PRs found."
            echo "found=false" >> $GITHUB_OUTPUT
          else
            echo "Matching PRs: ${MATCHING_PRS[*]}"
            printf "%s\n" "${MATCHING_PRS[@]}" > pr_list.txt
            echo "found=true" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge matching PRs
        if: steps.find_prs.outputs.found == 'true'
        run: |
          while read PR; do
            echo "Merging PR #$PR..."
            gh pr merge "$PR" --merge --delete-branch || echo "Failed to merge PR #$PR, skipping."
          done < pr_list.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
