name: Auto merge PRs with matching commit message

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find open PRs with commit message "archive json file"
        id: find_prs
        run: |
          echo "Searching for open PRs with commit message: archive json file"
          MATCH_MESSAGE="archive json file"
          MATCHING_PRS=()
      
          # Get all open PR numbers
          PR_NUMBERS=$(gh pr list --repo "$GITHUB_REPOSITORY" --state open --json number --jq '.[].number')
          echo "Found open PRs: $PR_NUMBERS"
      
          for PR in $PR_NUMBERS; do
            echo "---------------------------------------------"
            echo "Checking PR #$PR"
      
            # Fetch commits with both message and messageHeadline
            PR_JSON=$(gh pr view "$PR" --repo "$GITHUB_REPOSITORY" --json commits)
      
            # Extract messageHeadline and message if present
            HEADLINES=$(echo "$PR_JSON" | jq -r '.commits[].messageHeadline')
            MESSAGES=$(echo "$PR_JSON" | jq -r '.commits[].message // empty')
      
            FOUND_MATCH=false
      
            # Check messageHeadline
            while IFS= read -r LINE; do
              echo "messageHeadline: $LINE"
              if [[ "${LINE,,}" == *"${MATCH_MESSAGE,,}"* ]]; then
                FOUND_MATCH=true
                break
              fi
            done <<< "$HEADLINES"
      
            # If no match in messageHeadline, check full messages
            if [[ "$FOUND_MATCH" == false ]]; then
              while IFS= read -r LINE; do
                echo "message: $LINE"
                if [[ "${LINE,,}" == *"${MATCH_MESSAGE,,}"* ]]; then
                  FOUND_MATCH=true
                  break
                fi
              done <<< "$MESSAGES"
            fi
      
            if [[ "$FOUND_MATCH" == true ]]; then
              echo "Match found in PR #$PR"
              MATCHING_PRS+=("$PR")
            else
              echo "No match in PR #$PR"
            fi
          done
      
          if [ ${#MATCHING_PRS[@]} -eq 0 ]; then
            echo "No matching PRs found."
            echo "found=false" >> $GITHUB_OUTPUT
          else
            echo "Matching PRs: ${MATCHING_PRS[*]}"
            printf "%s\n" "${MATCHING_PRS[@]}" > pr_list.txt
            echo "found=true" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Merge matching PRs
        if: steps.find_prs.outputs.found == 'true'
        run: |
          while read PR; do
            echo "Merging PR #$PR..."
            gh pr merge "$PR" --merge --delete-branch || true
          done < pr_list.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
