name: Create Pull Request

on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  
jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make changes
        run: |
          echo "Some text" >> update.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Updated"
          branch: auto/update-changes
          title: "Automated PR from GitHub Actions"
          body: |
            This PR was created automatically by GitHub Actions.
          labels: automated-pr
